DROP TABLE IF EXISTS roomhasfacility CASCADE;
DROP TABLE IF EXISTS hotelamenity CASCADE;

DROP TABLE IF EXISTS amenity CASCADE;
DROP TABLE IF EXISTS roomfacility CASCADE;

DROP TABLE IF EXISTS room CASCADE;
DROP TABLE IF EXISTS users CASCADE;